### ISSUE TITLE
Clicking on the "Profile" button in Android crashes the whole app.

### ISSUE THREAD

**Issue by Ashvith** [AudiusProject/audius-client#1127] opened 2022-03-25 10:02 UTC
Title says it all. App crashes when I try to access the profile options on the bottom bar.

**Comment by Elandig** [comment] 2022-03-27 10:03
I'm experiencing the same issue. Any kind of profile opened immediately crashes the app.

**Comment by sliptype** [comment] 2022-04-01 14:04
Hey! We weren't immediately able to reproduce the issue. Can you make sure that the Audius app is fully updated?

Also could you let me know which device and version of android you are running?

**Comment by Ashvith** [comment] 2022-04-01 16:33
> Hey! We weren't immediately able to reproduce the issue. Can you make sure that the Audius app is fully updated?
> 
> Also could you let me know which device and version of android you are running?

Android version 11, device name is realme 5 pro.

**Comment by subutex** [comment] 2022-04-02 11:01
Hi, I've the same issue since some weeks ago. The Audius app version is 1.1.66 installed on Redmi Note 9 Pro running on Android 11. Everything is updated on my phone so far.

**Comment by subutex** [comment] 2022-04-07 07:10
This is very annoying because I can't access my profile anymore on my smartphone, I can only access my songs via notifications when someone forward or like them. And when I click on my song I can't share it on Twitter. When I click on the Twitter share button, Twitter app does not open. Could you please have a look at those issues ? Thank you in advance.

**Comment by sliptype** [comment] 2022-04-26 22:44
This is fixed in version 1.1.95, please upgrade and it should work!

Thanks for flagging 🙏

**Closed by sliptype** 2022-04-26 22:44 UTC

**Comment by subutex** [comment] 2022-04-27 00:14
Great, it works now ! Thank you 😊
